name: pullreq
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - develop         # Push events on master branch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: go build -v ./cmd/gocomu
    
    - name: Check that everything works
      run: ./gocomu new cli -name test
