name: release
on:
  push:
    tags:        
      - v* 
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Update version
      run:  cd $GITHUB_WORKSPACE && go run ./version/version.go

    - name: Commit files
      run: |
        git config --local user.email "ktc@pm.me"
        git config --local user.name "bh90210"
        git commit -m "Add changes" -a
  
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.gh_token }}

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.gh_token }}